server:
  port: 8084

spring:
  output:
    ansi:
      enabled: DETECT
  data:
    mongodb:
        uri: ${MONGO_DB_URL}
    web:
      pageable:
        max-page-size: 100000
        default-page-size: 100000
  mvc:
    log-request-details: true
  main:
    allow-bean-definition-overriding: true
  liquibase:
    enabled: false
    change-log: classpath:/db/changelog/changelog-master.xml
  kafka:
    bootstrap-servers: rocket-01.srvs.cloudkafka.com:9094,rocket-02.srvs.cloudkafka.com:9094,rocket-03.srvs.cloudkafka.com:9094
    properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${CLOUD_KARAFKA_USERNAME}" password="${CLOUD_KARAFKA_PASSWORD}";
        mechanism: SCRAM-SHA-256
      security:
        protocol: SASL_SSL
    template:
      default-topic: ${CLOUD_KARAFKA_TOPIC}
    consumer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: media-events-listener-group

eureka:
  client:
    enabled: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    fetchRegistry: true
    healthcheck:
      enabled: true
  instance:
    instance-id: ${spring.application.name}:${random.int}

ribbon:
  http:
    client:
      enabled: true
  https:
    client:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'

elasticsearch:
  host: ${ELASTICSEARCH_HOST}
  user: ${ELASTICSEARCH_USER}
  pass: ${ELASTICSEARCH_PASS}

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  level:
    root: info
    org.springframework: warn
    org.hibernate: info
    org.notabarista: info
    org.springframework.data.mongodb.core.MongoTemplate: INFO
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 2
  file:
    name: /var/log/${spring.application.name}.log
