server:
  port: 8084

spring:
  output:
    ansi:
      enabled: DETECT
  data:
    mongodb:
      uri: mongodb+srv://username:<password>@host/database?retryWrites=true&w=majority
    web:
      pageable:
        max-page-size: 100000
        default-page-size: 100000
  mvc:
    log-request-details: true
  main:
    allow-bean-definition-overriding: true
  liquibase:
    enabled: false
    change-log: classpath:/db/changelog/changelog-master.xml

eureka:
  client:
    enabled: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    healthcheck:
      enabled: true
  instance:
    instance-id: ${spring.application.name}:${random.int}

ribbon:
  http:
    client:
      enabled: true
  https:
    client:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  level:
    root: info
    org.springframework.data.mongodb.core.MongoTemplate: INFO
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 2
  file:
    name: /var/log/${spring.application.name}.log
